name: diversion_generator
version: 0.0.1
author: Edman Anjos <edmanjos@gmail.com>
description: Compile-time dependency injection library for Dart.
homepage: http://github.com/edman/diversion

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  diversion:
    path: ../diversion
  source_gen: ^0.9.0
  analyzer: '>=0.33.3 <0.36.0'
  analyzer_plugin: '>=0.0.1-alpha.5 <0.0.1-alpha.8'
  build: ^1.0.0
  build_config: ^0.3.1
  built_collection: '>=2.0.0 <5.0.0'
  built_value: '>=5.5.5 <7.0.0'
  quiver: '>=0.21.0 <3.0.0'

dev_dependencies:
  build_test: ^0.10.3
  build_runner: ^1.0.0
  logging: ^0.11.0
  test: ^1.0.0
